// Beebwatch, for Pebble
// by Tom Gidden <tom@gidden.net>
// May 4, 2013
//
// This code is hacked together from a number of sources, most notably the
// Pebble SDK examples; and https://github.com/dansl/pebble-silly-walk
// (for examples of image rotation)
//
// The code's a bit of a mess, but once the SDK settles down and is a bit
// better documented, I'll probably rework this code to match. Until then,
// my apologies: my code's not usually this messy.
//
// Copyright on the BBC Clock face design is probably held by the BBC,
// although I've redrawn it from scratch. Copyright on the fonts is held
// by me (Tom Gidden), but is based on the characters generated by the
// Mullard SAA5050 chip as used in Teletext.


#include "pebble_os.h"
#include "pebble_app.h"
#include "pebble_fonts.h"

#include "config.h"

#define NO 0
#define YES 1



#define FONT_SMALL RESOURCE_ID_FONT_MALLARD_16
#define FONT_LARGE RESOURCE_ID_FONT_MALLARD_CONDENSED_SUBSET_32


PBL_APP_INFO(MY_UUID, APP_NAME, "Tom Gidden",
             1, 1, /* App version */
             RESOURCE_ID_IMAGE_MENU_ICON, APP_INFO_WATCH_FACE);

Window window;

int firstrun = YES; // Variable to check for first run

BmpContainer watchface_container;
RotBmpPairContainer hourhand_container;
RotBmpPairContainer minutehand_container;

TextLayer date_layer;
TextLayer time_layer;
Layer sechand_layer;

GFont large_font;
GFont small_font;
GPoint center;
GRect watchface_frame;
GRect centerdot_rect;
int centerdot_radius = 9;

int sechand_length = 56;

static PblTm pebble_time;

static char date_text[] = "Xxx 00 Xxx";
static char *time_format;
static char time_text[] = "00:00:00";

void sechand_update_proc(Layer *me, GContext *ctx)
{
    if(seconds) {
        static GPoint endpoint1, endpoint2;

        graphics_context_set_stroke_color(ctx, GColorWhite);

        int32_t a = TRIG_MAX_ANGLE * pebble_time.tm_sec / 60;
        int16_t dy = (int16_t)(-cos_lookup(a) * (int32_t)sechand_length / TRIG_MAX_RATIO);
        int16_t dx = (int16_t)(sin_lookup(a) * (int32_t)sechand_length / TRIG_MAX_RATIO);

        endpoint1.x = center.x + dx;
        endpoint1.y = center.y + dy;
        endpoint2.x = center.x - dx/3;
        endpoint2.y = center.y - dy/3;

        graphics_draw_line(ctx, endpoint1, endpoint2);
    }

    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, centerdot_rect, centerdot_radius, GCornersAll);
}

void set_hand(RotBmpPairContainer *pair, int ang)
{
    pair->layer.white_layer.rotation = TRIG_MAX_ANGLE * ang / 360;
    pair->layer.black_layer.rotation = TRIG_MAX_ANGLE * ang / 360;
    layer_mark_dirty(&pair->layer.layer);
}

void handle_tick(AppContextRef ctx, PebbleTickEvent *t)
{
    (void)ctx;

    if(t)
        pebble_time = *t->tick_time;
    else
        get_time(&pebble_time);

    if(digital_time) {
        if (clock_is_24h_style()) {
            if(seconds) {
                time_format = "%R:%S";
            }
            else {
                time_format = "%R";
            }
        } else {
            if(seconds) {
                time_format = "%I:%M:%S";
            }
            else {
                time_format = "%I:%M";
            }
        }

        string_format_time(time_text, sizeof(time_text), time_format, &pebble_time);
        if ((!clock_is_24h_style()) && (time_text[0] == '0')) {
            time_text[0] = ' ';
        }

        text_layer_set_text(&time_layer, time_text);
    }

    if(seconds) {
        layer_mark_dirty(&sechand_layer);
    }

    if (firstrun || !seconds || (pebble_time.tm_sec == 0)) {
        set_hand(&hourhand_container, (pebble_time.tm_hour % 12)*30 + (pebble_time.tm_min/2));
        set_hand(&minutehand_container, pebble_time.tm_min*6);

        if(firstrun || pebble_time.tm_min == 0) {
            string_format_time(date_text, sizeof(date_text), "%a %e %b", &pebble_time);
            text_layer_set_text(&date_layer, date_text);
        }

        if(firstrun)
            firstrun = NO;
    }
}

void handle_init(AppContextRef ctx)
{
    (void)ctx;

    window_init(&window, APP_NAME);
    window_stack_push(&window, true /* Animated */);
    window_set_background_color(&window, GColorBlack);

    resource_init_current_app(&APP_RESOURCES);

    bmp_init_container(RESOURCE_ID_IMAGE_WATCHFACE, &watchface_container);

    watchface_frame = layer_get_frame(&watchface_container.layer.layer);
    watchface_frame.origin.x = 16;

    if(digital_time)
        watchface_frame.origin.y = 0;
    else
        watchface_frame.origin.y = 14;

    center = GPoint(watchface_frame.size.w/2, watchface_frame.size.h/2);
    centerdot_rect = GRect(center.x - centerdot_radius, center.y - centerdot_radius, centerdot_radius*2, centerdot_radius*2);

    layer_set_frame(&watchface_container.layer.layer, watchface_frame);
    layer_add_child(&window.layer, &watchface_container.layer.layer);

    large_font = fonts_load_custom_font(resource_get_handle(FONT_LARGE));
    small_font = fonts_load_custom_font(resource_get_handle(FONT_SMALL));

    // Date
    text_layer_init(&date_layer, window.layer.frame);
    text_layer_set_text_color(&date_layer, GColorWhite);
    text_layer_set_background_color(&date_layer, GColorClear);
    layer_set_frame(&date_layer.layer, GRect(13, 146, 144-13, 20));
    text_layer_set_font(&date_layer, small_font);
    text_layer_set_text_alignment(&date_layer, GTextAlignmentLeft);
    layer_add_child(&window.layer, &date_layer.layer);

    // Time
    if(digital_time) {
        text_layer_init(&time_layer, window.layer.frame);
        text_layer_set_text_color(&time_layer, GColorWhite);
        text_layer_set_background_color(&time_layer, GColorClear);
        if(seconds)
            layer_set_frame(&time_layer.layer, GRect(25, 112, 144-25, 32));
        else
            layer_set_frame(&time_layer.layer, GRect(43, 112, 144-43, 32));
        text_layer_set_font(&time_layer, large_font);
        text_layer_set_text_alignment(&time_layer, GTextAlignmentLeft);
        layer_add_child(&window.layer, &time_layer.layer);
    }

    // Hands
    rotbmp_pair_init_container(RESOURCE_ID_IMAGE_HOURHAND_WHITE, RESOURCE_ID_IMAGE_HOURHAND_BLACK, &hourhand_container);
    rotbmp_pair_layer_set_src_ic(&hourhand_container.layer, GPoint(2, 37));
    hourhand_container.layer.layer.frame.origin.x = watchface_frame.origin.x + center.x - hourhand_container.layer.layer.frame.size.w / 2;
    hourhand_container.layer.layer.frame.origin.y = watchface_frame.origin.y + center.y - hourhand_container.layer.layer.frame.size.h / 2;
    layer_add_child(&window.layer, &hourhand_container.layer.layer);

    rotbmp_pair_init_container(RESOURCE_ID_IMAGE_MINUTEHAND_WHITE, RESOURCE_ID_IMAGE_MINUTEHAND_BLACK, &minutehand_container);
    rotbmp_pair_layer_set_src_ic(&minutehand_container.layer, GPoint(1, 56));
    minutehand_container.layer.layer.frame.origin.x = watchface_frame.origin.x + center.x - minutehand_container.layer.layer.frame.size.w / 2;
    minutehand_container.layer.layer.frame.origin.y = watchface_frame.origin.y + center.y - minutehand_container.layer.layer.frame.size.h / 2;
    layer_add_child(&window.layer, &minutehand_container.layer.layer);

    layer_init(&sechand_layer, watchface_frame);
    sechand_layer.update_proc = &sechand_update_proc;
    layer_add_child(&window.layer, &sechand_layer);

    handle_tick(NULL, NULL);
}

void handle_deinit(AppContextRef ctx)
{
    (void)ctx;

    bmp_deinit_container(&watchface_container);
    rotbmp_pair_deinit_container(&hourhand_container);
    rotbmp_pair_deinit_container(&minutehand_container);
    if(digital_time)
        fonts_unload_custom_font(&large_font);
    fonts_unload_custom_font(&small_font);
    window_deinit(&window);
}

void pbl_main(void *params) {
    PebbleAppHandlers handlers = {
        .init_handler = &handle_init,
        .deinit_handler = &handle_deinit,
        .tick_info = {
            .tick_handler = &handle_tick,
            .tick_units = SECOND_UNIT
        }
    };

    if(seconds)
        handlers.tick_info.tick_units = SECOND_UNIT;
    else
        handlers.tick_info.tick_units = MINUTE_UNIT;

    app_event_loop(params, &handlers);
}
